# -*- coding: utf-8 -*-
"""labelreading.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BHCmx8YPO_mJ2Ph_k-EPqk4qzN3JZvcM
"""

pip install "paddleocr>=2.0.1"

!pip install imgaug==0.2.5

!pip install paddlepaddle

!pip install gTTS

!git clone https://github.com/PaddlePaddle/PaddleOCR

from paddleocr import PaddleOCR, draw_ocr 
from matplotlib import pyplot as plt 
import cv2 
import os

from paddleocr import PaddleOCR,draw_ocr
ocr = PaddleOCR(use_angle_cls=True, lang='en') # need to run only once to download and load model into memory
img_path = '/content/Resource_Label_Group_custom-pharmaceutical-labels-01.jpg'
result = ocr.ocr(img_path, cls=True)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)
# draw result
from PIL import Image
result = result[0]
image = Image.open(img_path).convert('RGB')
boxes = [line[0] for line in result]
txts = [line[1][0] for line in result]
scores = [line[1][1] for line in result]
im_show = draw_ocr(image, boxes, txts, scores, font_path='/content/PaddleOCR/doc/fonts/latin.ttf')
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')

ocr_model = PaddleOCR(lang='en')

img_path = '/content/Resource_Label_Group_custom-pharmaceutical-labels-01.jpg'

result = ocr_model.ocr(img_path)

result

for res in line:
    print(res[1][0])

boxes = [res[0] for res in line] 
txts = [res[1][0] for res in line]
scores = [res[1][1] for res in line]

txts

font_path = '/content/PaddleOCR/doc/fonts/latin.ttf'

img = cv2.imread(img_path) 


img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(15,15))

annotated = draw_ocr(img, boxes, txts, scores, font_path=font_path) 

plt.imshow(annotated)

print(txts)

my_texts =' '.join(txts)
my_texts

